apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate.yaml
  - tlsroute.yaml
  - serviceaccount.yaml
  - serviceaccount-admin.yaml
  - clustersecretstore.yaml
